version: '3.8'

services:
  keycloak:
    image: docker.io/keycloak/keycloak:25.0
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=password
    volumes:
      - ..:/mnt/keycloak
    working_dir: /mnt/keycloak
    ports:
      - 8080:8080
    tty: true
