version: '3.9'

services:
  keycloak:
    image: quay.io/keycloak/keycloak:22.0.4
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: password
    volumes:
      - ..:/workspaces/keycloak
    working_dir: /workspaces/keycloak
    ports:
      - 8080:8080
    command:
      - start-dev
